"""sync users table

Revision ID: 2759919f553d
Revises: 163bc9a43ab4
Create Date: 2026-03-11 22:57:41.647436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2759919f553d'
down_revision = '163bc9a43ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=False),
    sa.Column('responsible_person', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('implementation_date', sa.Date(), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_user_id'), ['user_id'], unique=False)

    op.create_table('rabbits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rabbit_id', sa.String(length=20), nullable=False),
    sa.Column('breed', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('cage_location', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_details', sa.String(length=100), nullable=True),
    sa.Column('weight_at_birth', sa.Float(), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rabbits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rabbits_rabbit_id'), ['rabbit_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_rabbits_user_id'), ['user_id'], unique=False)

    op.create_table('breeding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('male_rabbit_id', sa.Integer(), nullable=False),
    sa.Column('female_rabbit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pairing_date', sa.Date(), nullable=False),
    sa.Column('expected_birth_date', sa.Date(), nullable=False),
    sa.Column('actual_birth_date', sa.Date(), nullable=True),
    sa.Column('kits_born', sa.Integer(), nullable=True),
    sa.Column('kits_survived', sa.Integer(), nullable=True),
    sa.Column('birth_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['female_rabbit_id'], ['rabbits.id'], ),
    sa.ForeignKeyConstraint(['male_rabbit_id'], ['rabbits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breeding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breeding_female_rabbit_id'), ['female_rabbit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breeding_male_rabbit_id'), ['male_rabbit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_breeding_user_id'), ['user_id'], unique=False)

    op.create_table('feeding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rabbit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('cage_or_block', sa.String(length=20), nullable=False),
    sa.Column('feeding_time', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rabbit_id'], ['rabbits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feeding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feeding_rabbit_id'), ['rabbit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feeding_user_id'), ['user_id'], unique=False)

    op.create_table('growth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rabbit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('date_measured', sa.Date(), nullable=False),
    sa.Column('age_weeks', sa.Integer(), nullable=True),
    sa.Column('measurement_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rabbit_id'], ['rabbits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('growth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_growth_rabbit_id'), ['rabbit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_growth_user_id'), ['user_id'], unique=False)

    op.create_table('health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rabbit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.String(length=200), nullable=True),
    sa.Column('treatment_given', sa.Text(), nullable=True),
    sa.Column('medication', sa.String(length=200), nullable=True),
    sa.Column('dosage', sa.String(length=50), nullable=True),
    sa.Column('treatment_date', sa.DateTime(), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('veterinarian', sa.String(length=150), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rabbit_id'], ['rabbits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_rabbit_id'), ['rabbit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_user_id'), ['user_id'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('result_description', sa.Text(), nullable=False),
    sa.Column('result_type', sa.String(length=20), nullable=False),
    sa.Column('impact_assessment', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('outcome_date', sa.Date(), nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcomes_user_id'), ['user_id'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rabbit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(length=150), nullable=False),
    sa.Column('buyer_phone', sa.String(length=20), nullable=True),
    sa.Column('buyer_email', sa.String(length=120), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('weight_at_sale', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rabbit_id'], ['rabbits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_rabbit_id'), ['rabbit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_user_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.drop_column('avatar')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('full_name')
        batch_op.drop_column('username')

    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('twitter_handle', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profiles_pkey'))
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('hobbies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('profile_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('accounts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_user_id'))
        batch_op.drop_index(batch_op.f('ix_sales_rabbit_id'))

    op.drop_table('sales')
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_user_id'))
        batch_op.drop_index(batch_op.f('ix_outcomes_decision_id'))

    op.drop_table('outcomes')
    with op.batch_alter_table('health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_user_id'))
        batch_op.drop_index(batch_op.f('ix_health_rabbit_id'))

    op.drop_table('health')
    with op.batch_alter_table('growth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_growth_user_id'))
        batch_op.drop_index(batch_op.f('ix_growth_rabbit_id'))

    op.drop_table('growth')
    with op.batch_alter_table('feeding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feeding_user_id'))
        batch_op.drop_index(batch_op.f('ix_feeding_rabbit_id'))

    op.drop_table('feeding')
    with op.batch_alter_table('breeding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breeding_user_id'))
        batch_op.drop_index(batch_op.f('ix_breeding_male_rabbit_id'))
        batch_op.drop_index(batch_op.f('ix_breeding_female_rabbit_id'))

    op.drop_table('breeding')
    with op.batch_alter_table('rabbits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rabbits_user_id'))
        batch_op.drop_index(batch_op.f('ix_rabbits_rabbit_id'))

    op.drop_table('rabbits')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_user_id'))

    op.drop_table('decisions')
    # ### end Alembic commands ###
